name: MakeDiff

on:
  push:
    branches: [main]
    #paths: [ 'Notebook/**.ipynb' ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths: [ 'Notebook/**.ipynb' ]

env:
  DIFF_CMD: ./Tool/nbdiff_web_exporter.py
  DIFF_ARTIFACT_DIR: diff_artifacts
  DIFF_PATH: 'Notebook/**.ipynb'
  PORT: 8080
  NBDIME_VER: 4.0.1 
  SELENIUM_VER: 4.22.0 
  CHROMDRIVER_BINARY_VER: 126.0.6478.63.0 
  JUPYTER_SERVER_VER: 2.12.5
  BASE_BRANCH: main

jobs:
  #build:
  #  runs-on: ${{ matrix.platform }}
  #  strategy:
  #    fail-fast: false
  #    matrix:
  #      # https://help.github.com/articles/virtual-environments-for-github-actions
  #      platform:
  #        - ubuntu-latest  # ubuntu-20.04
  #      python-version: [3.9]
 
  #  steps:
  #  - uses: actions/checkout@v3
  #  - name: Set up Python ${{ matrix.python-version }}
  #    uses: actions/setup-python@v4
  #    with:
  #      python-version: ${{ matrix.python-version }}
  #  - name: Install dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      pip install tox==3.26.0 pytest nbdime==4.0.1
  get-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Switch to previous commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}^1
      - name: Get diff files
        run: |
          diff_files=$(git diff --name-only HEAD^1 HEAD)
          echo "Diff files: $diff_files"
          # ここから先に差分ファイルに対する処理を記述
          
  notebook_diff:
    runs-on: ubuntu-latest
    steps:
      - name: Check Env
        run: |
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_BASE_REF: ${GITHUB_BASE_REF}"
          echo "GITHUB_HEAD_REF: ${GITHUB_HEAD_REF}"
          echo "GITHUB_REF_CONTEXT: ${GITHUB_REF_CONTEXT}"
          diff_file=$(git show --name-only ${GITHUB_SHA})
          echo "diff_file: $diff_file"

      - name: Checkout source tree
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # ref: ${{github.head_ref}} # For Pull Request
      #- uses: browser-actions/setup-chrome@v1
      #  id: setup-chrome
      #  with:
      #    chrome-version: 126
      #    install-dependencies: true
      #- run: |
      #    ${{ steps.setup-chrome.outputs.chrome-path }} --version
      ##- name: Setup Chrome and ChromeDriver
      ##  uses: ./.github/actions/setup-chrome
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
              nbdime==${{ env.NBDIME_VER }} \
              selenium==${{ env.SELENIUM_VER }} \
              chromedriver_binary==${{ env.CHROMDRIVER_BINARY_VER }} \
              jupyter_server==${{ env.JUPYTER_SERVER_VER }}
          pip install tox==3.26.0 pytest
          pip list
      ##- name: Install package
      ##  run: |
      ##    pip install .
      - name: diff notebooks
        id: make-notebook-diffhtmls
        run: |
          mkdir ${{ env.DIFF_ARTIFACT_DIR }}
          #python ${{ env.DIFF_CMD }} --export-dir ./${{ env.DIFF_ARTIFACT_DIR }} --port ${{ env.PORT }}  origin/${GITHUB_BASE_REF} origin/${GITHUB_HEAD_REF} Test1.ipynb
          python ${{ env.DIFF_CMD }} --export-dir ./${{ env.DIFF_ARTIFACT_DIR }} --port ${{ env.PORT }}  origin/${{ env.BASE_BRANCH }} origin/test Test1.ipynb
          #nbdiff-web-exporter --export-dir ./export-dir --port 8080  origin/main origin/test-data data/notebook.ipynb
          #python ./Tool/nbdiff_web_exporter.py --export-dir ./export_data --port 8080  main test Test1.ipynb
          #python ./Tool/nbdiff_web_exporter.py --export-dir ./export_data --port 8080 --browser ${{ steps.setup-chrome.outputs.chrome-path }} origin/main origin/test Test1.ipynb
          #python ./Tool/nbdiff_web_exporter.py --export-dir ./export_data --port 8080 --browser disabled origin/main origin/test Test1.ipynb
          #python ./Tool/nbdiff_web_exporter.py --export-dir ./export_data --port 8080 --browser chrome origin/main origin/test Test1.ipynb
      #- name: check diff file is exists.
      #  run: |
      #    #ls ./export-dir/data/notebook.html
      #    ls ./export_data/Test1.html
      - uses: actions/upload-artifact@v4
        with:
          name: notebook_diffhtmls
          path: ./${{ env.DIFF_ARTIFACT_DIR }}/*
